version: "3.8"

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000:9000
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./myPorto:/var/www/myPorto
      - vendor-store:/work/backend/vendor
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./myPorto:/var/www/myPorto
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
      - node_modules-store:/work/backend/node_modules
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - php
  db:
    image: mysql:8.0
    container_name: db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
volumes:
  mysql-data:
  vendor-store:
  node_modules-store:
  dynamodb-local-data:
